
version: '{build}'
os: Windows Server 2012
platform:
  - x64
install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
build_script:
  - sbt clean compile
test_script:
  - sbt nobu/jdkPackager:packageBin
cache:
  - C:\sbt\
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
