language: scala
jdk:
  - oraclejdk8
scala:
   - 2.11.7
branches:
  only:
    - master
script:
    - cd sss.asado-common ; sbt clean test 
    - cd ../sss.asado-network ; sbt clean test
    - cd ../sss.asado-ledger ; sbt clean test
    - cd ../sss.asado-node ; sbt clean test 
    - cd ../test-rigs/message-sender ; sbt clean test
