language: scala

os:
  - linux
  - osx

jdk:
  - oraclejdk8

osx_image: xcode8.3
 
scala:
   - 2.12.6

branches:
  only:
    - master

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y fakeroot; else brew install fakeroot; fi
  - if [ $TRAVIS_OS_NAME = osx   ]; then sudo spctl --master-disable; fi

script: "sbt clean coverage test coverageReport coverageAggregate coveralls"

after_success: "sbt clean test jdkPackager:packageBin"

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "mcsherrylabs"
  - git config --local user.email "alan@mcsherrylabs.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: ${git_api_key}
  file: "/home/travis/build/mcsherrylabs/sss.asado/sss.asado-nobu/target/universal/jdkpackager/bundles/openstar-0.4.0.deb"
  skip_cleanup: true
