language: scala

os:
  - linux
  - osx

jdk:
  - oraclejdk8

osx_image: xcode8.3
 
scala:
   - 2.12.6

#branches:
#  only:
#    - master

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y fakeroot; else brew install fakeroot; fi
  - if [ $TRAVIS_OS_NAME = osx   ]; then sudo spctl --master-disable; fi

script: "sbt clean" # coverage test coverageReport coverageAggregate coveralls"

after_success:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sbt clean; sbt "node/dist"; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx"   ]]; then sbt clean; sbt "node/dist"; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx"   ]]; then sbt "nobu/jdkPackager:packageBin"; fi


deploy:
  on:
    tags: true
    all_branches: true
  prerelease: true
  draft: true
  provider: releases
  api_key: ${git_api_key}
  file_glob: true
  file:
   - "sss.asado-nobu/target/universal/jdkpackager/bundles/**"
   - "sss.asado-node/target/universal/*.zip"
  skip_cleanup: true
