language: scala

os:
  - linux
  - osx

jdk:
  - oraclejdk8

scala:
   - 2.12.6

branches:
  only:
    - master

script: "sbt clean coverage test jdkPackager:packageBin"

after_success: "sbt coverageReport coverageAggregate coveralls"

